// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC12sS4bmDOkTlif5lgiTf2MpBPVTgn78Y',
    appId: '1:116731140286:android:66b7d4cd01b86d2b3326ef',
    messagingSenderId: '116731140286',
    projectId: 'hungerwatch-cb019',
    databaseURL: 'https://hungerwatch-cb019-default-rtdb.firebaseio.com',
    storageBucket: 'hungerwatch-cb019.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4fuoujN65hYDSbFizcSfGny4yXO_scr0',
    appId: '1:116731140286:ios:cb0b136f0b38f5fe3326ef',
    messagingSenderId: '116731140286',
    projectId: 'hungerwatch-cb019',
    databaseURL: 'https://hungerwatch-cb019-default-rtdb.firebaseio.com',
    storageBucket: 'hungerwatch-cb019.appspot.com',
    iosClientId: '116731140286-f12aivmt081oc47ssfrmtmhaulk7craq.apps.googleusercontent.com',
    iosBundleId: 'com.example.hungerwatch',
  );
}
